[project]
name = "taskapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "orcchg", email = "prism.getprism@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "uvicorn[standard]>=0.52.1",
]

[project.scripts]
taskapi = "taskapi:main"

[tool.uv]
package = false
